fixtures:
  repositories:
    'stdlib': 'git://github.com/puppetlabs/puppetlabs-stdlib.git'
    'inifile': 'git://github.com/puppetlabs/puppetlabs-inifile'
    'nova': 'git://github.com/stackforge/puppet-nova.git'
  symlinks:
    'oslo': "#{source_dir}"
